services:
  - type: web
    name: safestreet
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_GENAI_USE_VERTEXAI
        value: FALSE
      - key: OWM_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
